/*@StepGroupList
{
  "groups": [
    "Fill_Member_Information.sg",
    "Fill_Membership_Details.sg",
    "Fill_Payment_Details.sg",
    "Click_Proceed_Button_On_BackDate_Popup.sg",
    "Add_Campaign_Code_NTUC.sg",
    "Submit_Application.sg",
    "Membership_Details.sg",
    "Input_Search_Referrer.sg",
    "GetExchangeID.sg",
    "Run_MGM_Batch_Job.sg",
    "Switch_back_to_Athena.sg",
    "MGM_Details.sg",
    "Referee_Verification.sg"
  ]
}
*/

// ************************** IMPORTANT **************************
// This file is auto-generated by PlayQ for Step Group.
// Do not edit it manually. File is auto-generated.
// Any changes done directly will be lost on the next generation.
// ***************************************************************

import { Given } from '@cucumber/cucumber';

Given('Step Group: -Fill_Member_Information.sg- -Fill Member Information-', async function () {
    /*StepGroup:Fill_Member_Information.sg
        * Comm: Store -value: "#{faker.custom.nric.generate({ prefix: 'S', yearOfBirth: 1985 })}" in -variable: "var.NRIC" -options: ""
        * Comm: Store -value: "#{faker.custom.person.fullName()}" in -variable: "var.NRIC.Name" -options: ""
        * Comm: Store -value: "#{faker.custom.nric.getYear('#{var.NRIC}')}" in -variable: "var.NRIC.Year" -options: ""
        * D365CRM: Click left menu -field: "Membership Management" then sub menu -field: "Membership Applications" -options: ""
        * Comm: Wait for milliseconds -seconds: "5000"
        * D365CRM: Click top menu button -field: "New" -options: ""
        * D365CRM: Wait and verify header -text: "New Membership Application" -options: "{partialMatch: true}"
        * D365CRM: Input text -fieldName: "NRIC/FIN" -text: "#{var.NRIC}" -options: ""
        * D365CRM: Input text -fieldName: "Full Name (as per NRIC)" -text: "#{var.NRIC.Name}" -options: ""
        * D365CRM: Input date into field -field: "Date of Birth" -date: "18/6/#{var.NRIC.Year}" -options: ""
        * Comm: Wait for milliseconds -seconds: "3000"
        * D365CRM: Select dropdown -fieldName: "Race" -value: "<Race>" -options: ""
        * D365CRM: Select dropdown -fieldName: "Gender" -value: "<Gender>" -options: ""
        * D365CRM: Select dropdown -fieldName: "Marital Status" -value: "<Marital_Status>" -options: ""
        * D365CRM: Select dropdown -fieldName: "Education Level" -value: "<Education_Level>" -options: ""
        * D365CRM: Input lookup -field: "Nationality" -text: "<Nationality>" -options: ""
        * D365CRM: Select dropdown -fieldName: "Residential Status" -value: "<Residential_Status>" -options: ""
        * D365CRM: Input text -fieldName: "Mobile Phone" -text: "<Mobile_Phone>" -options: ""
        * D365CRM: Select dropdown -fieldName: "Employment Type" -value: "<Employment_Type>" -options: ""
        * D365CRM: Input text -fieldName: "Occupation" -text: "<Occupation>" -options: ""
        * D365CRM: Input lookup -field: "Occupation Group" -text: "<Occupation_Group>" -options: ""
        * Comm: Wait for milliseconds -seconds: "3000"
        * D365CRM: Input lookup -field: "Company" -text: "<Company>" -options: ""
        * Comm: Wait for milliseconds -seconds: "3000"
        * D365CRM: Input text -fieldName: "Postal Code" -text: "<Postal_Code>" -options: ""
        * Comm: Wait for milliseconds -seconds: "2000"
        * D365CRM: Input text -fieldName: "Floor" -text: "<Floor>" -options: ""
        * Comm: Wait for milliseconds -seconds: "2000"
        * D365CRM: Input text -fieldName: "Unit" -text: "<Unit>" -options: ""
        * Comm: Wait for milliseconds -seconds: "2000"
        * D365CRM: Input text -fieldName: "Block No." -text: "<Block_No>" -options: ""
        * D365CRM: Input text -fieldName: "Building" -text: "<Building>" -options: ""
        * D365CRM: Input text -fieldName: "Street Name" -text: "<Street_Name>" -options: ""
        * D365CRM: Input text -fieldName: "Valid Address?" -text: "<Valid_Address>" -options: ""
    */
});

Given('Step Group: -Fill_Membership_Details.sg- -Fill Membership Details-', async function () {
    /*StepGroup:Fill_Membership_Details.sg
        * Comm: Generate first day of the last month in -format: "D/M/YYYY" into -variable "var.LastFirstDay"
        * D365CRM: Click tab -field: "Membership Details" -options: ""
        * D365CRM: Input lookup -field: "Union Code" -text: "<Union_Code>" -options: ""
        * D365CRM: Input lookup -field: "Branch Code" -text: "<Branch_Code>" -options: ""
    */
});

Given('Step Group: -Fill_Payment_Details.sg- -Fill Payment Details-', async function () {
    /*StepGroup:Fill_Payment_Details.sg
        * D365CRM: Click tab -field: "Payment Details" -options: ""
        * D365CRM: Wait for loader to disappear -field: "Loading" -options: ""
        * D365CRM: Click top menu buttons -field: "More commands for Payment Collection" and then sub menu -field: "New Payment Collection" -options: ""
        * D365CRM: Wait and verify header -text: "New Payment Collection" -options: "{partialMatch:true}"
        * D365CRM: Select dropdown -fieldName: "Payment Type" -value: "<Payment_Type>" -options: ""
        * D365CRM: Click button -text: "Save" -options: ""
        * D365CRM: Wait for loader to disappear -field: "progressbar" -options: ""
        * D365CRM: Click top menu buttons -field: "Action" and then sub menu -field: "Payment received" -options: ""
        * Comm: Wait for milliseconds -seconds: "3000"
        * D365CRM: Click top menu button -field: "Go back" -options: ""
        * Comm: Wait for milliseconds -seconds: "4000"
        * D365CRM: Click top menu buttons -field: "More commands for Recurring Payment Instruction" and then sub menu -field: "New Recurring Payment Instruction" -options: ""
        * D365CRM: Wait and verify header -text: "New Recurring Payment Instruction" -options: "{partialMatch: true}"
        * Comm: Wait for milliseconds -seconds: "2000"
        * D365CRM: Select dropdown -fieldName: "Recurring Payment set up type" -value: "<Recurring_Payment_setup_type>" -options: ""
        * D365CRM: Input lookup -field: "Bank" -text: "<Bank>" -options: ""
        * Comm: Wait for milliseconds -seconds: "2000"
        * D365CRM: Input text -fieldName: "Bank Account Number" -text: "<Bank_Account_Number>" -options: ""
        * D365CRM: Input lookup -field: "Bank Branch" -text: "<Bank_Branch>" -options: ""
        * D365CRM: Click top menu button -field: "Save" -options: ""
        * Comm: Wait for milliseconds -seconds: "3000"
    */
});

Given('Step Group: -Click_Proceed_Button_On_BackDate_Popup.sg- -Click proceed button on backdate popup-', async function () {
    /*StepGroup:Click_Proceed_Button_On_BackDate_Popup.sg
        * D365CRM: Wait for loader to disappear -field: "progressbar" -options: ""
        * D365CRM: Click -field: "Proceed" button on back date popup -options: ""
        * D365CRM: Click popup button -field: "OK" -options: ""
        * Comm: Wait for milliseconds -seconds: "2000"
        * D365CRM: Click popup button -field: "OK" -options: ""
    */
});

Given('Step Group: -Add_Campaign_Code_NTUC.sg- -Add Campaign Code for NTUC-', async function () {
    /*StepGroup:Add_Campaign_Code_NTUC.sg
        * D365CRM: Click tab -field: "Membership Details" -options: ""
        * D365CRM: Input lookup -field: "Campaign Code" -text: "<Campaign_Code>" -options: ""
        * D365CRM: Click top menu button -field: "Save" -options: ""
        * D365CRM: Click top menu button -field: "Refresh" -options: ""
    */
});

Given('Step Group: -Submit_Application.sg- -Submit Application-', async function () {
    /*StepGroup:Submit_Application.sg
        * D365CRM: Click top menu buttons -field: "Actions More Commands. Actions" and then sub menu -field: "Submit" -options: ""
        * D365CRM: Click popup button -field: "OK" -options: ""
        * D365CRM: Click popup button -field: "OK" -options: ""
    */
});

Given('Step Group: -Membership_Details.sg- -Membership Details-', async function () {
    /*StepGroup:Membership_Details.sg
        * Comm: Generate first day of the current month in -format: "DD/MM/YYYY" into -variable "var.FirstDayCurrentMonth"
        * D365CRM: Input lookup -field: "Union Code" -text: "<Union_Code>" -options: ""
        * D365CRM: Input lookup -field: "Branch Code" -text: "<Branch_Code>" -options: ""
        * D365CRM: Input date into field -field: "var.FirstDayCurrentMonth" -date: "#{var.LastFirstDay}" -options: ""
        * D365CRM: Click top menu button -field: "Save" -options: ""
    */
});

Given('Step Group: -Input_Search_Referrer.sg- -Input Search Referrer-', async function () {
    /*StepGroup:Input_Search_Referrer.sg
        * D365CRM: Click tab -field: "MGM and Membership Gift" -options: ""
        * Custom: Switches to iframe: "WebResource_referrerSearch" and clicks a button: "Search Referrer" and then switches back to the main content
        * Custom: Switches to iframe: "FullPageWebResource" and input -field: "Enter Full Name or Exchange ID" -text: "#{var.ExchangeID}" and then switches back to the main content
        * Custom: Switches to iframe: "FullPageWebResource" and clicks a button: "Search" and then switches back to the main content
        * Custom: Switches to iframe: "FullPageWebResource" and selects a radio button: "#{var.ExchangeID}" and then switches back to the main content
        * Custom: Switches to iframe: "FullPageWebResource" and clicks a button: "OK" and then switches back to the main content
    */
});

Given('Step Group: -GetExchangeID.sg- -Get Exchange ID-', async function () {
    /*StepGroup:GetExchangeID.sg
        * D365CRM: Click tab -field: "Member Information" -options: ""
        * Web: Get Value -field: "Exchange ID" -storeTo: "var.ExchangeID" -options: "{fieldType: 'input',pattern: 'd365crm'}"
    */
});

Given('Step Group: -Run_MGM_Batch_Job.sg- -Run MGM Batch Job-', async function () {
    /*StepGroup:Run_MGM_Batch_Job.sg
        * D365CRM: Switch app from -field:"NTUC ATHENA" to -field:"Batch Jobs Administration" -options: ""
        * D365CRM: Input text -fieldName: "Ask about data in this table." -text: "<Batch_Job>" -options: ""
        * Web: Press Enter -options: ""
        * D365CRM: Double click table cell with row -row: "1" and column -column: "1" -options: ""
        * D365CRM: Click top menu button -field: "Trigger Job" -options: ""
        * Comm: Wait for milliseconds -seconds: "4000"
        * Web: Click button -field: "OK" -options: "{pattern: 'd365crm'}"
        * Comm: Wait for milliseconds -seconds: "2000"
    */
});

Given('Step Group: -Switch_back_to_Athena.sg- -Switch Back to Athena-', async function () {
    /*StepGroup:Switch_back_to_Athena.sg
        * D365CRM: Switch app from -field:"Batch Jobs Administration" to -field:"NTUC ATHENA" -options: ""
        * Comm: Wait for milliseconds -seconds: "4000"
    */
});

Given('Step Group: -MGM_Details.sg- -MGM Details-', async function () {
    /*StepGroup:MGM_Details.sg
        * D365CRM: Click left menu -text: "MGM Details" -options: ""
        * D365CRM: Input text -fieldName: "Ask about data in this table." -text: "#{var.ExchangeID}" -options: ""
        * Web: Press Enter -options: ""
        * D365CRM: Double click table cell with row -row: "1" and column -column: "1" -options: ""
        * Comm: Wait for milliseconds -seconds: "3000"
        * D365CRM: Verify header control list column value -field: "1" -variableName: "var.MGMStatus" -expectedValue: "In Progress" -options: ""
    */
});

Given('Step Group: -Referee_Verification.sg- -Referee Verification-', async function () {
    /*StepGroup:Referee_Verification.sg
      * D365CRM: Click left menu -field: "Membership Management" then sub menu -field: "Gift Details" -options: ""
      * D365CRM: Input text -fieldName: "SearchBoxWithTypeAhead-input" -text: "#{var.ExchangeID}" -options: ""
      * Web: Press Enter -options: ""
      * D365CRM: Double click table cell with row -row: "1" and column -column: "1" -options: ""
      * D365CRM: Store header control list column value -field: "1" to variable -variableName: "var.RequestID" -options: ""
      * D365CRM: Click left menu -field: "Membership Management" then sub menu -field: "Memberships" -options: ""
      * D365CRM: Input text -fieldName: "SearchBoxWithTypeAhead-input" -text: "" -options: ""
      * D365CRM: Double click table cell with row -row: "1" and column -column: "1" -options: ""
      * D365CRM: Click tab -field: "MGM and Memberships" -options: ""
      * D365CRM: Verify input lookup field value -field: "ntuc_referredbyrequestid.fieldControl-LookupResultsDropdown_ntuc_referredbyrequestid_selected_tag_text" -value: "#{var.RequestID}" -options: ""
      * D365CRM: Verify input field value -field: "ntuc_referredbyrequestid.fieldControl-LookupResultsDropdown_ntuc_referredbyrequestid_selected_tag_text" -value: "#{var.RequestID}" -options: ""
    */
});
